import type { Dashboard } from "./types";
// Entirely synthetic. No mailbox data, private domains or real email excerpts.
export const demoDashboard: Dashboard = {
  demo: true,
  configured: false,
  authenticated: false,
  writesEnabled: false,
  accounts: [
    {
      id: "work",
      email: "alex@studio.example",
      name: "Trabajo",
      mode: "review",
      policy: {
        marketing: false,
        newsletters: false,
        protectedDomains: ["studio.example"],
      },
      connected: true,
      lastSync: "2026-09-10T14:30:00Z",
      watchExpires: null,
      lastError: null,
      reviewedAt: null,
    },
    {
      id: "personal",
      email: "alex@gmail.example",
      name: "Personal",
      mode: "paused",
      policy: { marketing: false, newsletters: false, protectedDomains: [] },
      connected: true,
      lastSync: null,
      watchExpires: null,
      lastError: null,
      reviewedAt: null,
    },
  ],
  decisions: [
    {
      id: "d1",
      accountId: "work",
      messageId: "demo-1",
      threadId: "demo-1",
      sender: "marcos@pipeline.example",
      subject: "Una idea para sumar reuniones a tu agenda",
      category: "cold",
      confidence: 0.99,
      reason:
        "Ofrece un servicio de prospección. No hay una conversación previa.",
      state: "suggested",
      createdAt: "2026-09-10T14:28:00Z",
    },
    {
      id: "d2",
      accountId: "work",
      messageId: "demo-2",
      threadId: "demo-2",
      sender: "ana@buildteam.example",
      subject: "Un equipo de desarrollo para tu próximo proyecto",
      category: "cold",
      confidence: 0.99,
      reason: "Propuesta comercial de un proveedor con el que no conversaste.",
      state: "suggested",
      createdAt: "2026-09-10T14:15:00Z",
    },
    {
      id: "d3",
      accountId: "work",
      messageId: "demo-3",
      threadId: "demo-3",
      sender: "sofia@north.example",
      subject: "Nos gustaría probar su producto",
      category: "personal",
      confidence: 0.9,
      reason: "Podría ser un cliente interesado. Se queda en tu bandeja.",
      state: "kept",
      createdAt: "2026-09-10T13:50:00Z",
    },
    {
      id: "d4",
      accountId: "work",
      messageId: "demo-4",
      threadId: "demo-4",
      sender: "equipo@notes.example",
      subject: "Novedades de septiembre",
      category: "newsletter",
      confidence: 0.98,
      reason: "Es un boletín. Todavía no elegiste apartar newsletters.",
      state: "kept",
      createdAt: "2026-09-10T13:20:00Z",
    },
  ],
  rules: [
    {
      id: "r1",
      accountId: "work",
      sender: "lucia@partner.example",
      createdAt: "2026-09-09T12:00:00Z",
    },
  ],
};
