import type { Dashboard } from "./types";
// Entirely synthetic. No mailbox data, private domains or real email excerpts.
export const demoDashboard: Dashboard = {
  demo: true,
  configured: false,
  authenticated: false,
  writesEnabled: false,
  accounts: [
    {
      id: "work",
      email: "alex@studio.example",
      name: "Work",
      mode: "review",
      policy: {
        marketing: false,
        newsletters: false,
        protectedDomains: ["studio.example"],
      },
      connected: true,
      writesEnabled: false,
      lastSync: "2026-09-10T14:30:00Z",
      watchExpires: null,
      lastError: null,
      reviewedAt: null,
    },
    {
      id: "personal",
      email: "alex@gmail.example",
      name: "Personal",
      mode: "paused",
      policy: { marketing: false, newsletters: false, protectedDomains: [] },
      connected: true,
      writesEnabled: false,
      lastSync: null,
      watchExpires: null,
      lastError: null,
      reviewedAt: null,
    },
  ],
  decisions: [
    {
      id: "d1",
      accountId: "work",
      messageId: "demo-1",
      threadId: "demo-1",
      sender: "marcos@pipeline.example",
      subject: "An idea to fill your calendar",
      category: "cold",
      confidence: 0.99,
      reason:
        "Offers a lead generation service. There is no prior conversation.",
      state: "suggested",
      createdAt: "2026-09-10T14:28:00Z",
    },
    {
      id: "d2",
      accountId: "work",
      messageId: "demo-2",
      threadId: "demo-2",
      sender: "ana@buildteam.example",
      subject: "A development team for your next project",
      category: "cold",
      confidence: 0.99,
      reason: "A sales pitch from a vendor you have not spoken with.",
      state: "suggested",
      createdAt: "2026-09-10T14:15:00Z",
    },
    {
      id: "d3",
      accountId: "work",
      messageId: "demo-3",
      threadId: "demo-3",
      sender: "sofia@north.example",
      subject: "We would like to try your product",
      category: "personal",
      confidence: 0.9,
      reason: "Could be an interested customer. It stays in your inbox.",
      state: "kept",
      createdAt: "2026-09-10T13:50:00Z",
    },
    {
      id: "d4",
      accountId: "work",
      messageId: "demo-4",
      threadId: "demo-4",
      sender: "equipo@notes.example",
      subject: "September updates",
      category: "newsletter",
      confidence: 0.98,
      reason: "This is a newsletter. You have not enabled moving newsletters.",
      state: "kept",
      createdAt: "2026-09-10T13:20:00Z",
    },
  ],
  rules: [
    {
      id: "r1",
      accountId: "work",
      sender: "lucia@partner.example",
      createdAt: "2026-09-09T12:00:00Z",
    },
  ],
};
